services:
  db:
    image: mysqlcompose # image personalizada criada no meu docker local...
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3307:3306"
    networks:
      - dockercompose

  backend:
    depends_on: # depende do container de cima para ser iniciado...
      - db
    image: flaskcompose # image personalizada criada no meu docker local...
    ports:
      - "5000:5000"
    restart: always
    volumes: # quero persistir os dados em tempo real do meu app.py (pra ver as alterações ao vivo)
      - "/home/diniz/Workspaces/docker_course/networks/conexao_entre_containers/flask:/app"
    networks:
      - dockercompose

networks: # o docker cria como padrão uma rede bridge
  dockercompose: